### ISSUE TITLE
Prometheus not scraping from Crudlex endpoint

### ISSUE THREAD

**Issue by dakala** [philiplb/PHPProm#2]
Great work! I'm doing an article on PHPProm and interested in writing an integration for Drupal 8. I've set up Prometheus locally with Crudlex also running on the same machine. However, I'm having issues with Prometheus not scraping from my endpoint. I can `curl` my `/metrics` endpoint, the data is visible in Redis but Prometheus is reporting status as "down" with the error "context deadline exceeded". 

Have I missed anything? Any assistance would be appreciated please.

**What I've done:**

- I added this to `web\index.php`:

```php
$storage = new PHPProm\Storage\Redis('localhost', ''); // /usr/local/etc/redis.conf

$silexPrometheusSetup = new PHPProm\Integration\SilexSetup();
$metricsAction = $silexPrometheusSetup->setupAndGetMetricsRoute($app, $storage);
$app->get('/metrics', $metricsAction);
```
- I added **my-job** to `prometheus.yml`:

```
# my global config
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'codelab-monitor'

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first.rules"
  # - "second.rules"
  - 'prometheus.rules'

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'my-job'
    scrape_interval: 20s
    static_configs:
      - targets: ['test-site.dev']
        labels:
          group: 'my-job-test'

  - job_name:       'example-random'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    static_configs:
      - targets: ['localhost:8080', 'localhost:8081']
        labels:
          group: 'production'

      - targets: ['localhost:8082']
        labels:
          group: 'canary'
```          

I've also filed an issue with Prometheus, perhaps it's a misconfiguration. Thanks.

**Comment by philiplb** [comment]
Hi,
great too see it used by someone. :)

What is the exact URL of the metrics endpoint? Does it have a path component, HTTPS or a basic auth? Here an example of all of them:

```yml
  - job_name: 'my-job'
    scrape_interval: 15s
    honor_labels: true
    scheme: https
    basic_auth:
      username: myUser
      password: myPassword
    metrics_path: /api/v1/metrics
    static_configs:
      - targets: ['my.domain.com']
        labels:
          group: 'myGroup'
```
